var mongoose = require('mongoose');

module.exports = mongoose.model('Auditionee',{
	id: String,
	firstName: String,
	lastName: String,
	dob: String,
	phone: String,
	email: String,
	address1: String,
	address2: String,
	city: String,
	state: String,
	zip: Number,
	school: String,
	schoolYear: String,
	pg1FirstName: String,
	pg1LastName: String,
	pg1Phone1: String,
	pg1Phone2: String,
	pg1Email: String,
	pg1Address1: String,
	pg1Address2: String,
	pg1City: String,
	pg1State: String,
	pg1Zip: String,
	referral: String,
	referralOther: String,
	yearsDrumming: String,
	experience: String,
	auditionInstrument1: String,
	auditionInstrument2: String,
	auditionInstrument3: String,
	specialTalents: String,
	conflicts: String,
	goal: String,
	submitDate: Date
});