FROM node:10.9-alpine

ENV APP_PATH=/home/node/pioneer_indoor

RUN apk add --update ca-certificates mysql-client python py-pip jq && \
		rm -rf /var/cache/apk/*
RUN pip install --upgrade pip && \
		pip install awscli

WORKDIR $APP_PATH
# using .dockerignore
COPY . .

ENV DB_SSL_CA_CERT=$APP_PATH/rds-combined-ca-bundle.pem

RUN npm i && \
	npm i pm2@3.1.3 -g
